#!/bin/bash

# TODO: repl mode, inotifywait mode, implicit dependencies, implicit rules
# configure, install, install-*, uninstall, all, test, dist (package), clean, doc,
# check, installcheck

# acceptable characters in function names: 1a*/~!@#%^*[]{}_-+=:.,?
# unacceptable characters in function names: <>$`'"&();\|
# to list all defined functions:
# compgen -A function [pattern]

set -o nounset
set -o errexit
set -o pipefail
shopt -s extglob
shopt -s globstar

{ # utility functions

  # convert a indexed or associative array value to a properly quoted string
  tostring () {
    local var="$(declare -p "$1")"
    eval echo "${var/#declare -? $1=}"
  }

  # return the body of a defined function. Usage:
  # . <(inline func_name)
  inline () {
    local fn="$(declare -f "$1")"
    echo "${fn/#$1 \(\)}"
  }

  # split a string using a delimiter character
  split () {
    local IFS="$1"
    set -- $2
    local array=("$@")
    tostring array
  }
}

{ # logging functions
  die () {
    echo "$@" 1>&2
    exit 1
  }

  warn () {
    if (( log_level >= 1 )); then
      echo "$@" 1>&2
    fi
  }

  log () {
    if (( log_level >= 2 )); then
      echo "$@" 1>&2
    fi
  }

  info () {
    if (( log_level >= 3 )); then
      echo "$@" 1>&2
    fi
  }

  debug () {
    if (( log_level >= 4 )); then
      echo "$@" 1>&2
    fi
  }
}

# rule function for determining sources for the target
depends () {
  "depends.$update_check" "$@"
}

# find the most specific rule that matches the specified target
# target rules get first priority, followed by pattern matching rules.
buildme.findrule () {
  local target="$1" fn rule file patrule

  # first get the list of rules:
  mapfile < <(compgen -A function)
  for fn in "${MAPFILE[@]}"; do
    case "$fn" in
      *[][*,?!@+{}]*:) # pattern matching rule
        # A few pattern matching characters are not allowed in function names.
        # Perform the following conversions as a workaround:
        # {{->( }}->) ,,->|
        # acceptable characters in function names: 0-9a-zA-Z*/~!@#%^*[]{}_-+=:.,?
        if [[ ! -n "$patrule" ]]; then
          fn="${fn%:}"
          fn="${fn//\{\{/\(}"
          fn="${fn//\}\}/\)}"
          fn="${fn//,,/\|}"
          pushd "$directory"
          for file in $fn; do
            if [[ "$target" -ef "$file" ]]; then
              patrule="$fn"
            fi
          done
          popd
        fi
        ;;
      *::) # phony target rule
        if [[ "$target" -ef "${fn%::}" ]]; then
          rule="$fn"
        fi
        ;;
      *:) # target rule
        if [[ "$target" -ef "${fn%:}" ]]; then
          rule="$fn"
        fi
        ;;
    esac
  done  
  if [[ -n "$rule" ]]; then
    echo "$rule"
    return
  elif [[ -n "$patrule" ]]; then
    echo "$patrule"
    return
  fi
  return 1
}

{ # update checking functions

  buildme.update_check.pre.exists () {
    [[ -e "$1" ]]
  }
  buildme.update_check.update.exists () {
    [[ -e "$1" ]]
  }

  buildme.update_check.pre.checksum () {
    [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]
  }
  buildme.update_check.update.checksum () {
    if [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]; then  
      return 1
    fi
    checksums["$1"]="$("$checksum_prog" "$1")"
    return 0
  }

  buildme.update_check.pre.mtime () {
    local prev_max_mtime="${max_mtime:-0}"
    max_mtime=0
    return 1
  }
  buildme.update_check.post.mtime () {
    local target_mtime="$(stat -c %Y "$1")"
    if (( max_mtime < target_mtime )); then
      max_mtime="$target_mtime"
      # target doesn't need update
      return 0
    fi
    # target needs update
    return 1
  }
  buildme.update_check.update.mtime () {
    local updated_target_mtime="$(stat -c %Y "$1")"
    if (( updated_target_mtime < max_mtime )); then
      # target was not updated
      return 1
    fi
    if (( max_mtime < prev_max_mtime )); then
      max_mtime="$prev_max_mtime"  
    fi
    # target successfully updated
    return 0
  }
}

# Build a target. By this time the target is known--there are no wildcards
# in the target name.
buildme.build () {
  # if this target was already built, return its stored result
  if [[ -n "${built["$*"]}" ]]; then 
    return "${built["$*"]}"
  fi

  # find the best rule for this target
  local rule=$(buildme.findrule "$1") 
  # determine if this rule is "phony"; we don't do an update check for these.
  local phony
  case "$rule" in 
    *::) phony='true' ;;
  esac

  # Check if the target needs updating. Some update methods can perform
  # this check before dependencies are built. Other methods, e.g. mtime
  # requires the dependencies to be looked up first.
  if [[ ! -n "$phony" && ! -n "$testmode"
      && -n "$(declare -F "buildme.update_check.pre.$update_check")" 
      && . <(inline "buildme.update_check.pre.$update_check") ]]; then
    built["$*"]=0
    return 0 
  fi

  # Run the rule in a subshell with errexit enabled. This allows
  # exception-like behavior if any dependency updates fail.
  # Source the returned build function if it was defined.
  unset -f build
  local output=$( 
    set -e
    "$rule" "$@" &>/dev/null
    declare -f build || true
  )
  eval "$output"
  unset -v output

  # Check if the target needs updating. The mtime check happens here.
  if [[ ! -n "$phony" && ! -n "$testmode"
      && -n "$(declare -F "buildme.update_check.post.$update_check")" 
      && . <(inline "buildme.update_check.post.$update_check") ]]; then
    built["$*"]=0
    return 0 
  fi

  # if a build function was specified and we're not in test mode
  if [[ -n "$(declare -F build)" && ! -n "$testmode" ]]; then
    # execute the build function in a sub-shell
    ("$build" "$@")
    # memoize result of building this target
    built["$*"]="$?"

    # update timestamp/checksum for this target
    if [[ ! -n "$phony"
        && -n "$(declare -F "buildme.update_check.update.$update_check")" ]]; then
      . <(inline "buildme.update_check.update.$update_check")
    fi
  fi
  unset -f build
}

# take an argument list and an array called optlist of the form:
#     ( 'a|option-a' "description"
#       'b|optionb=-' "description"
#       'c|optionc=a' "description"
#       'd|optiond=A' "description" )
# Create and return an associative array called opts, along with the args list
getoptions () {
  local args=("$@")
  local lookups
  declare -A lookups
  declare -A opts

  # build a lookup table for options
  local i=0 a aliases last
  while (( i < "${#optlist[@]}" )); do
    declare -a aliases="$(split '|' "${optlist["$i"]}")"
    last="${aliases[@]: -1}"
    for a in "${aliases[@]}"; do
      lookups["${a%=}"]="$last"
    done
    (( i += 2 ))
  done

  local j lookup optname arg value values convertopts
  i=0
  while (( i < "${#args[@]}" )); do
    arg="${args["$i"]}"
    case "${arg}" in
      -*) # if it's an option, remove it from args list
        unset args["$i"]
        args=("${args[@]}")
        # fall through
      # stop parsing options if we get a --
      --) break ;;
      # process long options
      --*)
        arg="${arg#--}" # remove leading dashes
        lookup="${lookups["${arg%%=}"]}" # lookup this option in the optlist lookup
        if [[ -n "$lookup" ]]; then
          optname="${lookup%%=}" #get the optname with any =value removed
          case "$lookup" in
            *=*) # parse an option value
              case "$arg" in
                *=*) value="${arg#=}" ;;
                *) value="${args["$i"]}"
                   unset args["$i"]
                   args=("${args[@]}")
              esac
              # fall through
            *=-) # string value
              opts["$optname"]="$value" 
              ;;
            *=a) # indexed array
              unset values
              declare -a values="${opts["$optname"]}" # string -> array
              values+=("$value") # append a new value
              opts["$optname"]="$(tostring values)" # array -> string
              ;;
            *=A) # associative array
              unset values
              declare -A values="${opts["$optname"]}" # string -> array
              case "$value" in 
                *=*) values["${value%%=}"]="${value#=}" ;;
                *) die "argument not a key-value pair: $value"
              esac
              opts["$optname"]="$(tostring values)" # array -> string
              ;;
            *) opts["$optname"]="$optname" ;;
          esac
        else
          die "unrecognized option: $opt"
        fi
        ;;
      # convert from short to long form
      -*)
        j=1
        convertopts=()
        while (( j++ < "${#arg}" )); do
          lookup="${lookups["${opt:j:1}"]}"
          if [[ -n "$lookup" ]]; then
            case "$lookup" in
              *=*) 
                if (( j < "${#opt}"-1 )); then 
                  value="${opt:j+1}"
                  convertopts+=("--${lookup%%=}" "$value")
                  break
                fi
                # fall through
              *) convertopts+=("--${lookup%%=}") ;;
            esac
          else
            die "unrecognized option: -${opt:j:1}"
          fi
        done
        # add the converted opts to args
        args=("${args[@]:0:i}" "${convertopts[@]}" "${args[@]:i}")
        ;;
      *) (( i++ )) ;;
    esac
  done
  # print the parsed options and arguments list
  declare -p args opts
}

# given a list of options and descriptions optlist, print a usage
# message displaying the options.
# The first argument is a message to display before the options list.
# The second argument is a message to dislay after the options list.
usage () {
  echo "$1"
  echo "Usage: "
  local i=0 a aliases desc last optline d
  while (( i < "${#optlist[@]}" )); do
    declare -a aliases="$(split '|' "${optlist[@]:i:1}")"
    declare -a desc="$(split $'\n' "${optlist[@]:i+1:1}")"
    optline='  '
    # print the option aliases
    for a in "${aliases[@]}"; do
      case "${a%=}" in
        ??*) optline+="--${a%=} " ;;
        *) optline+="-${a%=} " ;;
      esac
    done
    # print the option type
    last="${aliases[@]: -1}"
    case "$last" in
      *=*) 
        case "${last##=}" in 
          -) optline+=' value' ;;
          a) optline+=' value ...' ;;
          A) optline+=' key=value ...' ;;
        esac
    esac
    echo "$optline"
    # print the indented description
    for d in "${desc[@]}"; do
      echo "    $d"
    done
    echo
    (( i += 2 ))
  done
  echo "$2"
}

build! () {
  if (( "$#" > 0 )); then
    # build each specified target
    for target in "$@"; do
      buildme.build "$target"
    done
  elif [[ -n "$default" ]]; then
    # build the default target
    buildme.build "$default"
  else
    die "No default target specified in BUILD file"
  fi
}

{ # parse command-line options
  optlist=(
    'h|help' "display a help message."
  )
  eval "$(getoptions "$@")" # returns opts, args

  if [[ -n "${opts["help"]}" ]]; then
    usage "$0"
    exit 1
  fi
}


{ # find the project directory
  pushd
  directory="$(pwd)"
  while [[ ! -f "$directory/BUILD" ]]; do
    cd ..
    directory="$(pwd)"
    if [[ "$(pwd)" -eq '/' ]]; then
      die "Could not find BUILDME project build file in any parent directory"
    fi
  done 
  popd
}

{ # set defaults for project variables
  basename=$(basename "$directory")
  name=${${basename%%-}:-project}
  if [[ -f VERSION ]]
  then
    version=$(cat VERSION)
  fi
  version=${version:-${${basename#-}:-1.0.0}}

  description='unknown project'
  url=''
  license=()
  depends=()
  update_check='mtime' # valid values: mtime, checksum, exists

  outputDirectory="${directory}/build"
  sourceDirectory="${directory}/src"
  testDirectory="${directory}/test"

  installdir="/usr"
  configPath=(
    "$installdir/share/buildme/config" 
    /etc/conf.d/buildme.d 
    /etc/conf.d/buildme 
    ~/.buildme.d 
    ~/.buildme
    "$directory/buildme.d"
    )

  checksum_prog=md5sum
  # target checksums
  declare -A checksums

  log_level=2 # default log level
  default_action=build # default action
  default= # default build target
  testmode= # test mode (do not build)

  # memoized list of things already built during this run
  declare -A built
}

# source all configuration files
for path in "${configPath[@]}"; do
  if [[ -f "$path" ]]; then
    source "$path"
  elif [[ -d "$path" ]]; then
    for file in "$path/*"; do
      source "$file"
    done
  fi
done

# source the project file
source "$directory/BUILD"

# get the action
if (( "$#" > 0 )); then
  action="$1"
else
  action="$default_action"
fi
shift

# call the action with the targets
if [[ -n "$action" && -n "$(declare -F "$action!")" ]]; then
  "$action!" "$@"
else
  die "Undefined action: \"$action\""
fi

